### ISSUE TITLE
Multiple Tally Lights

### ISSUE THREAD

**Issue by Kevitto** [rpitv/atem-tally#3]
Quick question, is it possible to modify the config file to allow multiple tally lights on a single RPi?  I'm looking to use this as a tally switcher, with each light for up to 8 cameras connected to a single RPi instead of one RPi per tally.

Thanks!

**Comment by robere2** [comment]
Apologies for the delay. I believe this is already how it works, however I haven't touched this code in a while. It should allow for at least 4 per Raspberry Pi.

**Comment by robere2** [comment]
Will look into this more, because just looking at the code, it seems like you're right. However, worst case, you can create eight configs and run eight instances of the program, one for each tally.

**Comment by robere2** [comment]
This branch adds support for multiple tally lights:
https://github.com/rpitv/atem-tally/tree/add-multiple-tallys
It seemingly wasn't pushed, and I don't currently have the ability to test it due to the pandemic, however I was using it or some version of it in the past. If it doesn't work, please try the other solution I posted above, and at some point after the pandemic I hope to get it working and merged into master.

**Comment by Kevitto** [comment]
I'm sorry, I completely forgot I posted this a while back when I was working on this project.  I ended up just changing index file to retrieve a switch/case to control multiple tally lights, it is currently running 8 lights on a ATEM Studio Pro without a hitch.

We can definitely close the issue if you're not particularily inclined to add the functionality.  Thanks!

**Comment by robere2** [comment]
> I'm sorry, I completely forgot I posted this a while back when I was working on this project. I ended up just changing index file to retrieve a switch/case to control multiple tally lights, it is currently running 8 lights on a ATEM Studio Pro without a hitch.
> 
> We can definitely close the issue if you're not particularily inclined to add the functionality. Thanks!

Great, and it works well? Feel free to also share your code. I'll still keep this issue pinned until a final solution is merged after the pandemic.

**Comment by robere2** [comment]
Reopening so I don't forget about it :)

**Comment by robere2** [comment]
Merged
